* [2018-8-19 Sun] Because windows uwp will treate those folders whose name is isoCode such as 'zh-tw' in different way, I need to rename those folders. 
Now, this code can changing those folders' name with a prefix, such as 'iso_'.
So, once you have a folder name with a prefix, i.e., 'zh-tw' -> 'iso_zh-tw', this code will translate the words based on 'zh-tw'.
* [2018-4-10 Tue] Change the field name outJsFile to be outDefaultFile since Angular prefers the .ts file.
* [2018-4-6 Fri] For node code, you can debug it with VSCode
If you open this package with VSCode and run the bash code
#+begin_src sh
tsc&& node --inspect-brk dist/bin.js
#+end_src
then choose *Attach* and run in Debug, you can debug the code with breakpoint and line by line.
* [2018-4-6 Fri] Can work now.
After adding the declaration ~"types":"dist/index.d.ts",~ 
into *package.json* file, I can use ~import~ 
to use my package in my ~.ts~ file now.
* [2018-4-6 Fri] Can make directory and write a file forcely even if their sub-directories do not exist.
* [2018-3-31 Sat] Try to use jest to do the unit test.
Well, you need to run
#+begin_src sh
npm i -g jest
npm i --save-dev @types/jest
#+end_src
before you want to do the unit tests.
By the way, jest will automatically use babel-jest to pre-transpile your code to run something like 'await'.
Hm, so that I can test the one with ~Promise~.
* [2018-3-30 Fri] Follow the concept shown in the package [[https://github.com/shakyShane/json-ts][json-ts]].
I modified ~.gitignore~, ~tsconfig.json~ and ~package.json~ to tune this package to behave as that package.

Besides, I also add in a ts code named ~update-pageTexts.ts~ to see what will be happened.
* [2018-3-30 Fri] Initialize it
By executing

#+begin_src sh
mkdir i18n-page-texts
cd i18n-page-texts
npm init
git init
tsc --init
#+end_src

to Initialize it.
Then, commit it.